#!/bin/sh

NAME=realtek-8821cu
VERSION=5.12.0.4

# EXEMPT_POSTINST is used to bypass the 'set -e' command which makes the script exit immediately if a command exits with a non-zero status.
# This is useful when the script is expected to fail in some cases.
[ -z "$EXEMPT_POSTINST" ] && set -e

# Enable debugging if DEBUG is defined
[ -n "$DEBUG" ] && set -x

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $NAME -v $VERSION --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
